### PR TITLE
testing to see if docs fail

### PR DESCRIPTION
**Pull request by edublancas**
## Issue ticket number and link
Closes #x 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

----
:books: Documentation preview :books:: https://sklearn-evaluation--252.org.readthedocs.build/en/252/

### CODE REVIEW

**Comment by idomic** [comment]
Maybe we should skip this example of model.fit, the problem is every notebook has something similar.

**Comment by edublancas** [comment]
trying again with a downgraded version of scikit-learn, there was a release two days ago, so that might be the reason

**Comment by edublancas** [comment]
fixed! I migrated papermill calls to ploomber-engine, and it works now!

**Comment by idomic** [comment]
looks good.

**Pull request merged**
