### PR TITLE
Docs reorganisation 

### LINKED ISSUE #283: orgs reorganization: classification
The documentation is becoming messy, so we need to re-organize it.

The classification section has the following sub-sections:

1. basic plots (old tutorial using functional API)
2. compare classifiers (recent tutorial, using object-oriented API)
3. evaluating classifiers (recent tutorial, with tools not covered in the other sections)
4. class imbalance (plots for class imbalance)
5. grid search (`RandomForestClassifierGrid`)
6. calibration (tutorial on probability calibration)

I suggest consolidating it into this:

1. Evaluation (how do I evaluate a classifier? show the most common plots: confusion matrix, classification report, ROC, and precision-recall)
2. Comparison (how do I compare two classifiers? show the same plots as above but the composed versions that allow comparing two models)
3. Optimization (how do I ensure the best performance?)
4. Tracking (how do I track experiments?)
5. Reporting (how do I generate a model evaluation report?)
6. Class imbalance
7. Calibration

## 1. evaluation

we can take the existing content from "basic plots". The objective is to have the most common plots and descriptions for each and use the new object-oriented API. We'll no longer include the functional API in the tutorials (except when a given plot only has a functional implementation) but we'll keep them in the API docs.

## 2. comparison

we can use the content from "compare classifiers". here we include the same plots as in "1. evaluation", except we show how to create the composed plots with `a+b` and `a - b`.

## 3. Optimization

we can move this [existing content](https://sklearn-evaluation.ploomber.io/en/latest/optimization/grid_search.html), and also include the content of [this](https://sklearn-evaluation.ploomber.io/en/latest/classification/grid_search.html), but shorten it so this section doesn't end up too long

## 4. tracking

we can use this [existing content](https://sklearn-evaluation.ploomber.io/en/latest/comparison/SQLiteTracker.html). but let's create a shorter version of the existing content. the idea is that the "tracking" tutorial under the "classification" section should be a short tutorial, and the existing, generic "tracking tutorial" should contain a deep dive into the features, we should also link from the former to the latter

## 5. reporting

move the [existing content](https://sklearn-evaluation.ploomber.io/en/latest/comparison/report.html)

## 6. class imbalance and 7. calibration

use existing content

## evaluating classifiers

Unsure about what to do about [this one](https://sklearn-evaluation.ploomber.io/en/latest/classification/evaluate.html); these aren't common plots, so I think we can remove the tutorial and move the content to the API docs.

---

thoughts on this, @neelasha23?

### PR DESCRIPTION
**Pull request by neelasha23**
## Issue ticket number and link
Closes #283 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [x] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

----
:books: Documentation preview :books:: https://sklearn-evaluation--297.org.readthedocs.build/en/297/

### CODE REVIEW

**Comment by neelasha23** [comment]
Couple of queries:

1. The `optimization` section : There are four plots here : Confusion matrix, ROC, feature importances and Grid search results. If we want to shorten this tutorial we can just retain `Grid search results` plot and remove `Confusion matrix`,  `ROC`, `feature importances` and add reference to some other doc for these plots. Currently there isn't an API Reference for `RandomForestClassifierGrid` so should it be added ?
2. Since Grid search is now moved to the classification section, the `model optimization` section now contains `Feature Ranking` only. Does this need to be here or moved to some other section?

@edublancas

**Comment by edublancas** [comment]
> The optimization section : There are four plots here : Confusion matrix, ROC, feature importances and Grid search results. If we want to shorten this tutorial we can just retain Grid search results plot and remove Confusion matrix, ROC, feature importances and add reference to some other doc for these plots. Currently there isn't an API Reference for RandomForestClassifierGrid so should it be added ?

I agree, let's just keep the grid search results plot. mention that there are other plots available and link to the API docs (we need to create the API docs) so let's create a new `sklearn_evaluation.grid` section in the docs and put it there. Let's also add some embedded examples in the docstring.

> Since Grid search is now moved to the classification section, the model optimization section now contains Feature Ranking only. Does this need to be here or moved to some other section?

Looks like this methods are generic, right? they could be used in classification or regression. If so, I think it's fine to leave them there, we can decide later

**Review by edublancas — CHANGES_REQUESTED** [review]
address the comments above

**Comment by neelasha23** [comment]
Made the changes
@edublancas

**Review by edublancas — CHANGES_REQUESTED** [review]
Made the above changes.

> I think you mentioned something about some error in this plot, right?

This was fixed. I think the plots are showing up only when we are calling the `from_raw_data` method and assigning to a variable. Not sure why this is happening.

**Comment by neelasha23** [comment]
Made the above changes.

> I think you mentioned something about some error in this plot, right?

This was fixed.  I think the plots are showing up only when we are calling the from_raw_data method and assigning to a variable. Not sure why this is happening.

@edublancas

**Pull request merged**
