### PR TITLE
removed n_clusters from elbow_curve

### LINKED ISSUE #190: Deprecation: `elbow_curve` will change its signature in version 0.9
`n_clusters` renamed to `range_n_clusters` and will be removed in version 0.9

we should remove `n_cluster` from 

```
def elbow_curve(
    X,
    clf,
    range_n_clusters=None,
    n_jobs=1,
    show_cluster_time=True,
    ax=None,
    n_clusters=None,
)
```

cc:
@idomic @edublancas

### PR DESCRIPTION
**Pull request by WSShawn**
## Describe your changes
removed n_clusters from elbow_curve()

## Issue ticket number and link
Closes #190 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [x] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

----
:books: Documentation preview :books:: https://sklearn-evaluation--247.org.readthedocs.build/en/247/

### CODE REVIEW

**Comment by WSShawn** [comment]
still working on fixing the test_clustering.oy file

**Comment by edublancas** [comment]
as a general tip: open the PR until it's ready. if you want to open a PR for early feedback or to test the CI, mark is as a draft

**Comment by idomic** [comment]
@WSShawn the CI is failing, converting to draft

**Comment by WSShawn** [comment]
Sorry for all the commits, I'll mark it as draft first next time. Also, do we have any experience dealing with the Tcl installation error before? I'm not sure what that means. @edublancas @idomic

**Comment by edublancas** [comment]
tcl is a conda error, trigger the CI again to fix it

**Comment by WSShawn** [comment]
@edublancas need some help with the readthedocs error.

**Comment by edublancas** [comment]
the error is: `_queue.Empty`. I've seen this before, it's an intermittent error in the jupyter-client, nothing we can do but to rebuild the docs. i re-triggered the build https://readthedocs.org/projects/sklearn-evaluation/builds/19287048/

**Comment by WSShawn** [comment]
Thanks! Let's see how it goes this time.

**Comment by WSShawn** [comment]
I think it's the same error again

**Comment by edublancas** [comment]
ok, looked at the error. I think the real reason is the timeout - there is one cell in a notebook that's taking longer than expected. check out the jupyter-book documentation, I remember seeing how to extend the cell timeout; if that doesn't work, then we'd need to investigate why this is failing. perhaps we can reduce the runtime of that cell to fix it

**Comment by WSShawn** [comment]
@edublancas found [this](https://nbsphinx.readthedocs.io/en/0.3.5/timeout.html) about cell execution timeout. Is this what we want? If yes, which file did we use to set up sphinx? Thanks!

**Comment by gtduncan** [comment]
Having the same issue, seems to be set in docs/conf.py? (looking at `execution_timeout = 30`)

**Comment by WSShawn** [comment]
Thanks! Any specific value did you use to fix this? @gtduncan

**Comment by gtduncan** [comment]
It seems to fail even when I set it fairly high (120 seconds), maybe it's something wrong with the cell

**Comment by WSShawn** [comment]
@edublancas could this cell be trying to extract n_clusters? 

Here is a preview of the cell contents:
-------------------
['# models with their corresponding parameters', 'params = [{', "    'model': 'sklearn.ensemble.RandomForestRegressor',", "    'params': {", "        'n_estimators': 50"]
...
["files = [f'{i}.ipynb' for i in ids]", '', '# execute notebooks using papermill', 'for f, p in zip(files, params):', "    pm.execute_notebook('train.ipynb', output_path=f, parameters=p)"]
-------------------

**Comment by idomic** [comment]
@WSShawn try to run those examples locally with your changes and see if it fails. I don't think the two are related.

**Comment by edublancas** [comment]
remember to also delete the deprecation message in the docstring, the one that begins with `.. deprecated:: 0.9`

**Comment by WSShawn** [comment]
ok, I'll delete it tonight after my class

**Review by edublancas — APPROVED** [review]

**Pull request merged**
