### PR TITLE
applies pending deprecation to confusion matrix

### PR DESCRIPTION
**Pull request by edublancas**
## Describe your changes

Applied a pending deprecation, updated an example, and fixed the overlapping plots (but only for the confusion matrix)

## Issue ticket number and link
Closes #x 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

----
:books: Documentation preview :books:: https://sklearn-evaluation--208.org.readthedocs.build/en/208/

### CODE REVIEW

**Review by idomic — APPROVED** [review]
lgtm

**Comment by WSShawn** [comment]
Hi I have some questions for issue 211. 
1. For the other plots with overlapping, do I also need to fix doc and changelog? What are these two files for?
2. What is the pending deprecation for and do I need to do the same for each and every other plot?
3. How does the last commit in this PR work? I can only see the addition of "@modify_exceptions" in this commit but it is for deploying the test. Do I need to put this line for every other plot's tests? 
4. Where am I supposed to find the baseline images for other plots? To be more clear, if baseline image for a specific plot type is missing, where should I go find it? 
Forgive me if some questions look dumb but I need to figure these out first to understand the current tests and write the tests.

**Comment by edublancas** [comment]
issue 211 is only about changing `plt.gca` for `plt.subplot`, no need to do anything else!

**Comment by WSShawn** [comment]
I thought I should also fix tests for other plots modified. If so please let me know.

**Pull request merged**
