### PR TITLE
Split API section in docs (PR 2)

### LINKED ISSUE #172: split API section into functional and object-oriented
we currently have a listing of all our `plot` API in  a single section: https://sklearn-evaluation.ploomber.io/en/latest/api/plot.html

I think it'd be better to split it in functional and object-oriented

```
object-oriented
----------------

ROC
ConfusionMatrix
...

functional
----------

roc
confusion_matrix
...


```

We should also use the [seealso](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-seealso) directive to link from roc <-> ROC and all others. 

Furthermore, we need to explain that the functional API is the easiest to get started, but the object-oriented one offers more flexibility to compare models

### PR DESCRIPTION
**Pull request by yafimvo**
## Describe your changes
1. API section split into functions and OOP
2. `.. seealso::` added to docs

## Issue ticket number and link
Closes #172 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

----
:books: Documentation preview :books:: https://sklearn-evaluation--216.org.readthedocs.build/en/216/

### CODE REVIEW

**Comment by idomic** [comment]
I think the [sections](https://sklearn-evaluation--216.org.readthedocs.build/en/216/api/plot.html#classificationreport) doesn't show on the sidebar?

**Comment by idomic** [comment]
Ok yes, bold and underline it, I didn't even notice, sorry for that.

**Comment by yafimvo** [comment]
@idomic I'm not sure it's possible to mark and underline sidebar contents (went over jupyter-book docs and other docs).

The closest thing I was able to do is indentation which reveals its content on scroll/click
image

**Comment by idomic** [comment]
Checking!

**Comment by yafimvo** [comment]
Didn't find out how to do it.
[I asked them](https://github.com/executablebooks/meta/discussions/920)

**Comment by idomic** [comment]
Let's see if they have anything, meanwhile I'll merge it in.

**Pull request merged**
