### PR TITLE
Updated Validating Elbow Curve Input Model

### LINKED ISSUE #146: Validating input model `plot.elbow_curve`
I found out that `plot.elbow_curve` only works with Kmeans, MiniBatchKMeans, and BisectingKMeans; since it relies on the `.score` method. We should validate the input model and throw an error if necessary.

something like:

```python
if not hasattr(clf, "score"):
    raise ValueError("clf does not have a score method. Ensure it's one of KMeans, ....")
```

### PR DESCRIPTION
**Pull request by gtduncan**
## Describe your changes

Validating that the input model for elbow_curve is one of the following: KMeans, MiniBatchKMeans, BisectingKMeans.

## Issue ticket number and link
Closes #146 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

----
:books: Documentation preview :books:: https://sklearn-evaluation--219.org.readthedocs.build/en/219/

### CODE REVIEW

**Comment by idomic** [comment]
CI's failing

**Comment by gtduncan** [comment]
I think the CI is failing trying to import BisectingKMeans... the error is given there and I think it may be because the CI is installing scikit_learn-1.0.2. I looked it up and BisectingKMeans was added in 1.1. 

Screen Shot 2023-01-17 at 12 43 23 PM

Screen Shot 2023-01-17 at 12 43 39 PM

**Comment by edublancas** [comment]
many python libraries dropped support for python 3.7 - that's why the CI is breaking.

we need to add a conditional flag (pytest has a skipif feature) to only run BisectingKMeans if python > 3.7. and we also need to ensure BisectingKMeans is not imported, otherwise it'll still fail

**Comment by idomic** [comment]
So it's not the scikit-learn version?

**Comment by edublancas** [comment]
> So it's not the scikit-learn version?

it is. scikit-learn 1.1 cannot be installed on Python 3.7

**Comment by idomic** [comment]
@gtduncan something around `@pytest.mark.skipif(sys.version_info == (3, 7))`, you'd need to cover the import as well, maybe add it into the test.

**Review by idomic — APPROVED** [review]
looks good, let's see the CI is passing.

**Comment by idomic** [comment]
Nice job!

**Pull request merged**
