### PR TITLE
fixes incorrect elbow_curve results

### PR DESCRIPTION
**Pull request by yafimvo**
`_clone_and_score_clusterer` method fixed

issue : #192

### CODE REVIEW

**Comment by idomic** [comment]
@yafimvo What's this PR/Issue about?

**Comment by yafimvo** [comment]
@idomic after changing the `n_clusters` to `range_n_clusters` in [this PR](https://github.com/ploomber/sklearn-evaluation/pull/182), I noticed `elbow_curve` displays an incorrect plot.

We didn't have a test for it so I fixed it and added a new test.

**Review by idomic — APPROVED** [review]
looks good

**Comment by edublancas** [comment]
ran this on binder and got the right result:

image


closing

**Pull request merged**
