### PR TITLE
fixes inline plots in tutorial

### PR DESCRIPTION
**Pull request by edublancas**
## Describe your changes

- I noticed the [tracker tutorial](https://sklearn-evaluation.ploomber.io/en/latest/comparison/SQLiteTracker.html#rendering-plots-in-table-view) had a lot of duplicated plots (see the link), this fixes it
- this also applies a pending deprecation on ClassificationReport

## Issue ticket number and link
Closes #x 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

### CODE REVIEW

**Review by idomic — COMMENTED** [review]
Where is it documented?
Aren't there guides that will be affected by this change?

**Comment by edublancas** [comment]
> Where is it documented?

what? the deprecation? It was a pending deprecation, check out the changes

**Comment by idomic** [comment]
No no I mean this one: `no_display_plots`

**Comment by edublancas** [comment]
Nothing has changed. `no_display_plots` is a context manager that's only applied when it's needed outside of it, behavior remains the same, check out the implementation

**Review by yafimvo — COMMENTED** [review]
lgtm.

Can the `no_display_plots` context affect the user experience when working with notebooks?

**Comment by edublancas** [comment]
> Can the no_display_plots context affect the user experience when working with notebooks?

no, it won't.`no_display_plots` is only used when de-serializing plots from JSON stored in a database. We shouldn't display them in such cases since we're loading them to put them in a table-view.

**Pull request merged**
