### PR TITLE
Migration of docs to jupyter-book

### PR DESCRIPTION
**Pull request by neelasha23**
Migrating all the existing docs to jupyter-book
Converting some .rst files to .ipynb format

### CODE REVIEW

**Comment by neelasha23** [comment]
There are a couple of issues in this PR which I haven't been able to solve yet and still checking:
1. Version of project is not showing up
2. Some extra cells are appearing the `Querying notebooks with SQL` guide.
3. docs CI for auto publish is not yet tested.

Query:
Do we need the `indices and table` section. Specifically the `search` subsection in it (there is already a search bar present)
@idomic @edublancas 

Currently it's hosted [here](https://neelasha23.github.io/sklearn-evaluation/intro.html). I have compared with the existing docs on `readthedocs` and looks ok. I'm still looking at how to host on a custom domain.

**Comment by idomic** [comment]
@neelasha23 can you add in the readme instructions on running testing locally?

**Comment by neelasha23** [comment]
@idomic It's added in the documentation/README.md file. Once your run the `build` command it will display the url of the html index file on local

**Comment by idomic** [comment]
@neelasha23 what else is missing here?
ETA for review?

**Comment by neelasha23** [comment]
I'm not able to make the binder links work. The existing code is generating custom links in the `hooks.py` file. I'm not sure how to do a similar thing through the `_config.yml` file because in jupyter-book the `conf.py` file is not the convention. The other features are done.

**Comment by edublancas** [comment]
good point. we can no longer use the old Binder logic. I'll take a look later with directions on how we can fix this

**Comment by edublancas** [comment]
also, I see there are some file conflicts, please resolve

**Comment by neelasha23** [comment]
yes fixing it.

**Comment by idomic** [comment]
@neelasha23 is that the only thing that's missing?
We can do the first round without binder for now (which doesn't exist on the current docs anyways), then add it to the JB.

**Comment by neelasha23** [comment]
yes that's the only thing left. The binder is present in the current docs for the notebooks. There are some conflicts currentlyI will resolve and update. Also, the CI is not getting triggered for the past few commits. Is it disabled for this PR?

**Comment by neelasha23** [comment]
Resolved the conflicts. This is ready for review
@edublancas @idomic

**Comment by edublancas** [comment]
great work! the docs look a lot better know. I found some minor issues

- there's a typo here: https://github.com/neelasha23/sklearn-evaluation/tree/jupyter_books/docs The folder is `docs` not, `documentation`
- the clustering_evaluation notebook is broken, I saw a few cells with errors
- please migrate some legacy files to notebook format (example user_guide/matplotlib)
- there are cases where a cell in a notebook has a long output (example: nbs/nbdb.html, indexing-notebooks section). we can tell jupyterbook to hide the output for that specific cell
- In the API reference, the right side bar does not show the function's names, this makes navigation difficult

image

**Comment by neelasha23** [comment]
> * the clustering_evaluation notebook is broken, I saw a few cells with errors

Can you please share a screenshot? I reloaded the page after clearing cache and I'm not able to see any errors [this link](https://docs.sklearn-evaluation.ploomber.io/en/latest/nbs/clustering_evaluation.html)

@edublancas

**Comment by edublancas** [comment]
I compiled the docs locally since I didn't know they were hosted already, maybe it's an error on my local setup. we can ignore this.

how come are the docs served from https://docs.sklearn-evaluation.ploomber.io if this PR hasn't been merged? I looked into readthedocs config and I couldn't find the domain configuration. I guess @idomic modified the DNS configuration but I still don't understand where the deployment is coming from if this code hasn't been merged

**Comment by neelasha23** [comment]
I have created a subdomain and configured in my own `readthedocs` account . I'll remove it once PR is merged.

**Comment by edublancas** [comment]
FYI: looks like if we want the right bar to list all the functions in a module, we have to list them one by one :/

see https://jupyterbook.org/en/stable/advanced/developers.html

**Comment by neelasha23** [comment]
Fixed all the review comments
@edublancas @idomic

**Comment by idomic** [comment]
- Are some of the sections merged on purpose?
i.e [comparing classifiers](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/compare.html) and [evaluating binary classifiers](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/evaluating_binary_classifiers.html) had subsections and are now under a single title.
- Can the sections be collapsed by default? showing just the main sections vs the inner menus.
- [Here](https://docs.sklearn-evaluation.ploomber.io/en/latest/community/community.html), try just linking the titles, no need to have the specific link below.

Besides that looks good!

**Comment by neelasha23** [comment]
> * Are some of the sections merged on purpose?
>   i.e [comparing classifiers](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/compare.html) and [evaluating binary classifiers](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/evaluating_binary_classifiers.html) had subsections and are now under a single title.

Yes I just merged together classifier evaluation related notebooks under a single section.

> * Can the sections be collapsed by default? showing just the main sections vs the inner menus.
Do you mean the `User guide`, `Api` and `Community`? I need to check, but I think this is how it is designed. It uses a construct called `Parts`

@idomic

**Comment by neelasha23** [comment]
> * [Here](https://docs.sklearn-evaluation.ploomber.io/en/latest/community/community.html), try just linking the titles, no need to have the specific link below.

Resolved this one.

**Comment by idomic** [comment]
> Do you mean the User guide, Api and Community? I need to check, but I think this is how it is designed. It uses a construct called Parts

Yes exactly!

> Yes I just merged together classifier evaluation related notebooks under a single section.

Ok, I think let's keep it like the original for now. Then we can have a session to improve structure etc.

**Comment by neelasha23** [comment]
> > Do you mean the User guide, Api and Community? I need to check, but I think this is how it is designed. It uses a construct called Parts
> 
> Yes exactly!

I'm referring to this [parts guide](https://jupyterbook.org/en/stable/structure/configure.html?highlight=parts). I haven't been to find any option for collapsing parts. The collapse option is there for sections, e.g in this [link](https://jupyterbook.org/en/stable/structure/toc.html?highlight=parts), `topic guide` is a part, and `Structure and organise content` is a section. But do we want to convert `User Guide` , etc to sections? I think `sections` should be reserved for grouping similar guides when we do the reorganising.

> > Yes I just merged together classifier evaluation related notebooks under a single section.
> 
> Ok, I think let's keep it like the original for now. Then we can have a session to improve structure etc.

Made this change.

Query:  Do we need to keep a backup of the previous `docs` folder? Because it will be overwritten once this PR is merged.

**Comment by idomic** [comment]
1. Let's leave it like this for now. Please open an issue in there and see what they respond (also on the second thing we tried achieving with the side bar). I found [this](https://github.com/executablebooks/jupyter-book/issues/1708) but I'm not sure it overlaps with the main topic collapse.
2. We don't need a backup, it's fine that the PR will overwrite it.

**Comment by idomic** [comment]
I think this is ready.
Please set the URL to [sklearn-evaluation.ploomber.io](http://sklearn-evaluation.ploomber.io/) (no leading docs).
Then we'll need to redirect the existing URL into this one as well (https://sklearn-evaluation.readthedocs.io/).
Once the routes are set I can merge it.

**Comment by idomic** [comment]
@neelasha23 [This one](https://docs.sklearn-evaluation.ploomber.io/en/latest/source/nbs/NotebookCollection.html?highlight=svm) is still failing?

**Comment by neelasha23** [comment]
> 1.I found [this](https://github.com/executablebooks/jupyter-book/issues/1708) but I'm not sure it overlaps with the main topic collapse.

I think this is for hiding output/ input of jupyter notebook cells. We are using it in some notebooks.

**Comment by neelasha23** [comment]
> I think this is ready. Please set the URL to [sklearn-evaluation.ploomber.io](http://sklearn-evaluation.ploomber.io/) (no leading docs). Then we'll need to redirect the existing URL into this one as well (https://sklearn-evaluation.readthedocs.io/). Once the routes are set I can merge it.

This is currently configured in my personal `readthedocs` account. It needs to be setup in ploomber's account.

**Comment by neelasha23** [comment]
> @neelasha23 [This one](https://docs.sklearn-evaluation.ploomber.io/en/latest/source/nbs/NotebookCollection.html?highlight=svm) is still failing?

This is weird. I did a rebuild of the docs and it looks fine now. Do you still see it ? @idomic 
I think it might be because readthedocs is not doing a clean build. I'm looking at solutions if any. Do we already have configuration to do a clean build?

**Comment by idomic** [comment]
It does show now, weird.
I'm not sure about that, I found a guide to clean it, but not sure if there's a flag to automatically clean cache.
```
To perform a clean build on ReadTheDocs, you can do the following:

Go to your project's settings page on ReadTheDocs.
In the "Advanced Settings" section, click the "Clear Builds" button. This will remove all previous builds of your documentation.
In the same section, you can also click the "Purge All Files" button to remove all files that were generated during the build process.
After clearing the builds and purging the files, you can trigger a new build of your documentation by clicking the "Build" button on the project's dashboard page. This will rebuild your documentation from scratch, using the latest version of your source files.

Note that the "Clear Builds" and "Purge All Files" options are only available if you have the necessary permissions for your project. These options may not be available if you are a member of a project with read-only access.
```
I think if it works for now that's what matters, please fix the conflicts, the URL, and double check there's no errors in the notebooks so we can merge.

@edublancas thoughts?

**Comment by idomic** [comment]
I think last time we did it via AWS - R53 (on
docs.sklearn-evaluation.ploomber.io)

**Comment by neelasha23** [comment]
I have created this subdomain: `sklearn-evaluation.ploomber.io`

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
awesome! 🎉

**Pull request merged**
