### PR TITLE
added roc1 + roc2 for compare.md

### LINKED ISSUE #227: ROC example missing in compare section
we should add the roc1 + roc2 here: https://sklearn-evaluation.ploomber.io/en/latest/classification/compare.html

### PR DESCRIPTION
**Pull request by WSShawn**
## Describe your changes
added roc1 + roc2 for compare.md
## Issue ticket number and link
Closes #227 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

----
:books: Documentation preview :books:: https://sklearn-evaluation--234.org.readthedocs.build/en/234/

### CODE REVIEW

**Comment by idomic** [comment]
@WSShawn make sure the [docs](https://sklearn-evaluation--234.org.readthedocs.build/en/234/) are visible once you're done

**Comment by edublancas** [comment]
the header levels are incorrect:

image

let's create a new ROC section and put the ROC-related subsections under it

**Comment by WSShawn** [comment]
ok

**Comment by WSShawn** [comment]
I was able to add a new ROC section but on the menu bar, it does not show the subsections.

**Comment by edublancas** [comment]
they show up once you scroll. looks good, if the CI passes, I'll merge!

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
great work!

**Pull request merged**
