### PR TITLE
fix overlapping plots

### PR DESCRIPTION
**Pull request by WSShawn**
## Describe your changes
fixed overlapping plots

## Issue ticket number and link
Closes #x 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

----
:books: Documentation preview :books:: https://sklearn-evaluation--211.org.readthedocs.build/en/211/

### CODE REVIEW

**Comment by idomic** [comment]
I see no tests, please check [this pr](https://github.com/ploomber/sklearn-evaluation/pull/208), it has sample confusion matrix plot tests, add the necessary tests for each plot.

**Comment by WSShawn** [comment]
Hey so I was reading through the PR you mentioned. I have some questions regarding how to deploy the test "for each plot" and where am I supposed to find the correct baseline images. Would be super helpful if there could be a tutorial session for this. Thank you.

**Comment by edublancas** [comment]
in my sample confusion matrix test, I'm generating multiple plots (e.g., cm1 + cm2), so it's easy to test the `subplot`, because I just check that many image files are generated. For cases where we're testing single images, I think it'll be better to mock `plt`, and then test that `subplots` has been called - that would be enough to test we won't have overlapping plots

**Comment by idomic** [comment]
A change in the values inside is fine, the main thing to check is that there's no weird stuff with the plots: missing labels, overlapping text, etc.

**Comment by WSShawn** [comment]
Yeah I did not see any of those problems!

**Comment by edublancas** [comment]
please also share screenshots so we can better judge the differences

**Comment by edublancas** [comment]
also, let's change the changelog and tag this as `[API Change]`, as it impacts the API

**Comment by WSShawn** [comment]
should we modify the changelog for 0.9.0 or 0.9.1? 
Screenshot 2023-01-16 at 11 37 25 AM

**Comment by idomic** [comment]
Always the dev version.

**Comment by edublancas** [comment]
change 0.9.1.dev -> 0.10dev and also update the value in the src/sklearn_evaluation/__init__.py to 0.10dev, then put your changelog entry under 0.10dev

**Comment by WSShawn** [comment]
got it. just to make sure, it will look like this:

CHANGELOG

0.10.0dev
BP [API Change] Fixed overlapping plot issue (#211)

0.9.0 (2023-01-13)
...

**Review by edublancas — APPROVED** [review]

**Pull request merged**
