### PR TITLE
Remove pinned pydata version

### PR DESCRIPTION
**Pull request by tl3119**
## Issue number

Closes #X

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://sklearn-evaluation--335.org.readthedocs.build/en/335/

### CODE REVIEW

**Comment by edublancas** [comment]
@tl3119: this is blocked by https://github.com/ploomber/sklearn-evaluation/issues/336  - let's focus on the other repositories until that one is fixed

**Comment by edublancas** [comment]
@tl3119 I think this has been fixed. please push an empty commit to trigger the CI, and let me know if all tests pass

**Comment by tl3119** [comment]
> @tl3119 I think this has been fixed. please push an empty commit to trigger the CI, and let me know if all tests pass

readthedocs test fails. I click the test, and the page crushes.

**Comment by edublancas** [comment]
did you merge from master? https://github.com/ploomber/sklearn-evaluation/pull/337 fixed that

**Comment by tl3119** [comment]
> did you merge from master? #337 fixed that

All tests pass now

**Pull request merged**
