### PR TITLE
adds precision-recall multiclass example

### LINKED ISSUE #238: missing multiclass precision-recall examples
we're missing multiclass examples in `plot.precision_recall`: https://sklearn-evaluation.ploomber.io/en/latest/api/plot.html#precision-recall

### PR DESCRIPTION
**Pull request by ShubhamGawande191**
## Describe your changes
This change resolves #238 by adding a precision-recall multiclass example
## Issue ticket number and link
Closes #238  

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

----
:books: Documentation preview :books:: https://sklearn-evaluation--241.org.readthedocs.build/en/241/

### CODE REVIEW

**Comment by idomic** [comment]
Thanks for contributing!

**Comment by edublancas** [comment]
@ShubhamGawande191 we have some other issues where we need help, do you wanna take it? https://github.com/ploomber/sklearn-evaluation/issues/217

**Comment by ShubhamGawande191** [comment]
Yes, would love to. Assign me #217

**Comment by edublancas** [comment]
great! please add a comment on #217, github won't let me assign it to you unless you post there

**Pull request merged**
